name: fcai_hu
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  flip_card: ^0.6.0
  flutter_offline: ^2.1.0
  flutter_unity: ^0.3.0
  full_screen_image_null_safe: ^2.0.0
  hexcolor: ^2.0.7
  number_paginator: ^0.0.2
  splash_screen_view: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/